import type { ITrack } from "../model/types";

export const tracks: ITrack[] = [
  {
    id: 0,
    img: "backtofriends.png",
    name: "Back to of friends",
    author: 0,
    file: "Sombr - Back to friends.mp3",
  },
  {
    id: 1,
    img: "cureforme.jpg",
    name: "Cure For Me",
    author: 1,
    file: "AURORA - Cure For Me.mp3",
  },
  {
    id: 2,
    img: "cureforme.jpg",
    name: "Runaway",
    author: 1,
    file: "AURORA - Runaway.mp3",
  },
  {
    id: 3,
    img: "endofbeginning.png",
    name: "End of Beginning",
    author: 2,
    file: "Djo - End of Beginning.mp3",
  },
  {
    id: 4,
    img: "formedbyglaciers.jpg",
    name: "Formed by Glaciers",
    author: 3,
    file: "Kubbi - Formed by Glaciers.mp3",
  },
  {
    id: 5,
    img: "paperplanes.png",
    name: "Paper Planes",
    author: 4,
    file: "M.I.A. - Paper Planes.mp3",
  },
  {
    id: 6,
    img: "scottstreet.jpg",
    name: "Scott Street",
    author: 5,
    file: "Phoebe Bridgers - Scott Street.mp3",
  },
  {
    id: 7,
    img: "selfharm.png",
    name: "Селфхарм",
    author: 6,
    file: "Монеточка - Селфхарм.mp3",
  },
  {
    id: 8,
    img: "×øneheart x reidenshi - snowfall.jpg",
    name: "snowfall",
    author: 7,
    file: "×øneheart x reidenshi - snowfall.mp3",
  },
  {
    id: 9,
    img: "Beach House - Space Song.jpg",
    name: "Space Song",
    author: 8,
    file: "Beach House - Space Song.mp3",
  },
  {
    id: 10,
    img: "bôa - Duvet.png",
    name: "Duvet",
    author: 9,
    file: "bôa - Duvet.mp3",
  },
  {
    id: 11,
    img: "Edward Maya ft. Vika Jigulina - Stereo love.jpg",
    name: "Stereo love",
    author: 10,
    file: "Edward Maya ft. Vika Jigulina - Stereo love.mp3",
  },
  {
    id: 12,
    img: "Kaguya-sama wa Kokurasetai OST vol. 2 - 21. Souiu natsu (そういう夏).jpg",
    name: "Kaguya-sama wa Kokurasetai OST vol. 2 - 21.",
    author: 11,
    file: "Kaguya-sama wa Kokurasetai OST vol. 2 - 21. Souiu natsu (そういう夏).mp3",
  },
  {
    id: 13,
    img: "mzlff, BOOKER - ящики.jpg",
    name: "ящики",
    author: 12,
    file: "mzlff, BOOKER - ящики.mp3",
  },
  {
    id: 14,
    img: "Nirvana - Heart-Shaped Box.jpg",
    name: "Heart-Shaped Box",
    author: 13,
    file: "Nirvana - Heart-Shaped Box.mp3",
  },
  {
    id: 15,
    img: "Sidewalks and Skeletons - Goth (Slowed + Reverb).jpg",
    name: "Goth (Slowed + Reverb)",
    author: 14,
    file: "Sidewalks and Skeletons - Goth (Slowed + Reverb).mp3",
  },
  {
    id: 16,
    img: "selfharm.png",
    name: "Это было в России",
    author: 6,
    file: "Монеточка - Это было в России.mp3",
  },
];
