import { LeftBar } from "@/widgets/LeftBar";
import { Author } from "./Author/index";
import { AuthorsList } from "./AuthorsList";
import { Favorites } from "./Favorites/index";
import { MainSwiper } from "./MainSwiper/index";
import { MusicList } from "./MusicList/index";
import { MusicPlayer } from "./MusicPlayer/index";
import { NotFound } from "./NotFound";
import { SearchWithHistory } from "./SearchWithHistory/index";
export { Author, AuthorsList, Favorites, LeftBar, MainSwiper, MusicList, MusicPlayer, NotFound, SearchWithHistory };
